module.exports = {
    darkMode: "class",
    content: ["./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            fontFamily: {
                sans: [
                    "-apple-system",
                    "BlinkMacSystemFont",
                    "SF Pro Text",
                    "Inter",
                    "Helvetica Neue",
                    "Arial",
                    "sans-serif",
                ],
                mono: [
                    "SF Mono",
                    "Roboto Mono",
                    "monospace",
                ],
            },
            fontSize: {
                xs:  ["12px", "16px"],
                sm:  ["14px", "20px"],
                base:["16px", "24px"],
                lg:  ["18px", "26px"],
                xl:  ["20px", "28px"],
                "2xl":["24px", "32px"],
                "3xl":["30px", "38px"],
                "4xl":["36px", "44px"],
            },
            spacing: {
                xs: "4px",
                sm: "8px",
                md: "12px",
                lg: "16px",
                xl: "24px",
                "2xl": "32px",
                'safe-top': 'var(--safe-top)',
                'safe-bottom': 'var(--safe-bottom)',
            },
            borderRadius: {
                xs: "6px",
                sm: "8px",
                md: "12px",
                lg: "16px",
                xl: "20px",
                full: "9999px",
            },
            colors: {
                primary: {
                    0: "rgb(var(--primary-0) / <alpha-value>)",
                    50: "rgb(var(--primary-50) / <alpha-value>)",
                    100: "rgb(var(--primary-100) / <alpha-value>)",
                    200: "rgb(var(--primary-200) / <alpha-value>)",
                    300: "rgb(var(--primary-300) / <alpha-value>)",
                    400: "rgb(var(--primary-400) / <alpha-value>)",
                    500: "rgb(var(--primary-500) / <alpha-value>)",
                    600: "rgb(var(--primary-600) / <alpha-value>)",
                    700: "rgb(var(--primary-700) / <alpha-value>)",
                    800: "rgb(var(--primary-800) / <alpha-value>)",
                    900: "rgb(var(--primary-900) / <alpha-value>)",
                    1000: "rgb(var(--primary-1000) / <alpha-value>)",
                    DEFAULT: "rgb(var(--primary-500) / <alpha-value>)",
                },

                secondary: {
                    0: "rgb(var(--secondary-0) / <alpha-value>)",
                    50: "rgb(var(--secondary-50) / <alpha-value>)",
                    100: "rgb(var(--secondary-100) / <alpha-value>)",
                    200: "rgb(var(--secondary-200) / <alpha-value>)",
                    300: "rgb(var(--secondary-300) / <alpha-value>)",
                    400: "rgb(var(--secondary-400) / <alpha-value>)",
                    500: "rgb(var(--secondary-500) / <alpha-value>)",
                    600: "rgb(var(--secondary-600) / <alpha-value>)",
                    700: "rgb(var(--secondary-700) / <alpha-value>)",
                    800: "rgb(var(--secondary-800) / <alpha-value>)",
                    900: "rgb(var(--secondary-900) / <alpha-value>)",
                    1000: "rgb(var(--secondary-1000) / <alpha-value>)",
                    DEFAULT: "rgb(var(--secondary-500) / <alpha-value>)",
                },

                ink: {
                    0: "rgb(var(--ink-0) / <alpha-value>)",
                    50: "rgb(var(--ink-50) / <alpha-value>)",
                    100: "rgb(var(--ink-100) / <alpha-value>)",
                    200: "rgb(var(--ink-200) / <alpha-value>)",
                    300: "rgb(var(--ink-300) / <alpha-value>)",
                    400: "rgb(var(--ink-400) / <alpha-value>)",
                    500: "rgb(var(--ink-500) / <alpha-value>)",
                    600: "rgb(var(--ink-600) / <alpha-value>)",
                    700: "rgb(var(--ink-700) / <alpha-value>)",
                    800: "rgb(var(--ink-800) / <alpha-value>)",
                    900: "rgb(var(--ink-900) / <alpha-value>)",
                    1000: "rgb(var(--ink-1000) / <alpha-value>)",
                    DEFAULT: "rgb(var(--ink-900) / <alpha-value>)",
                },

                danger: {
                    0: "rgb(var(--danger-0) / <alpha-value>)",
                    50: "rgb(var(--danger-50) / <alpha-value>)",
                    100: "rgb(var(--danger-100) / <alpha-value>)",
                    200: "rgb(var(--danger-200) / <alpha-value>)",
                    300: "rgb(var(--danger-300) / <alpha-value>)",
                    400: "rgb(var(--danger-400) / <alpha-value>)",
                    500: "rgb(var(--danger-500) / <alpha-value>)",
                    600: "rgb(var(--danger-600) / <alpha-value>)",
                    700: "rgb(var(--danger-700) / <alpha-value>)",
                    800: "rgb(var(--danger-800) / <alpha-value>)",
                    900: "rgb(var(--danger-900) / <alpha-value>)",
                    1000: "rgb(var(--danger-1000) / <alpha-value>)",
                    DEFAULT: "rgb(var(--danger-500) / <alpha-value>)",
                },
                success: {
                    0: "rgb(var(--success-0) / <alpha-value>)",
                    50: "rgb(var(--success-50) / <alpha-value>)",
                    100: "rgb(var(--success-100) / <alpha-value>)",
                    200: "rgb(var(--success-200) / <alpha-value>)",
                    300: "rgb(var(--success-300) / <alpha-value>)",
                    400: "rgb(var(--success-400) / <alpha-value>)",
                    500: "rgb(var(--success-500) / <alpha-value>)",
                    600: "rgb(var(--success-600) / <alpha-value>)",
                    700: "rgb(var(--success-700) / <alpha-value>)",
                    800: "rgb(var(--success-800) / <alpha-value>)",
                    900: "rgb(var(--success-900) / <alpha-value>)",
                    1000: "rgb(var(--success-1000) / <alpha-value>)",
                    DEFAULT: "rgb(var(--success-500) / <alpha-value>)",
                },

                warning: {
                    0: "rgb(var(--warning-0) / <alpha-value>)",
                    50: "rgb(var(--warning-50) / <alpha-value>)",
                    100: "rgb(var(--warning-100) / <alpha-value>)",
                    200: "rgb(var(--warning-200) / <alpha-value>)",
                    300: "rgb(var(--warning-300) / <alpha-value>)",
                    400: "rgb(var(--warning-400) / <alpha-value>)",
                    500: "rgb(var(--warning-500) / <alpha-value>)",
                    600: "rgb(var(--warning-600) / <alpha-value>)",
                    700: "rgb(var(--warning-700) / <alpha-value>)",
                    800: "rgb(var(--warning-800) / <alpha-value>)",
                    900: "rgb(var(--warning-900) / <alpha-value>)",
                    1000: "rgb(var(--warning-1000) / <alpha-value>)",
                    DEFAULT: "rgb(var(--warning-500) / <alpha-value>)",
                },
            },

            backgroundImage: {
                "primary-gradient":
                    "linear-gradient(135deg, #7c3aed 0%, #5b21b6 100%)",
                "primary-soft":
                    "linear-gradient(135deg, #ede9fe 0%, #f7f5ff 100%)",
            },
            screens: {
                "xs": "360px",
            },
        },
    },
    plugins: [],
}

